"""Figures 1-9, all regenerated by `venomgap figures`. Vector PDF plus PNG, units on every axis.

Every number plotted is read from `results/*.json`. Nothing is retyped, so a figure can never drift
away from the result it depicts.

Colour follows the validated reference palette: categorical hues assigned in fixed order and never
cycled, a single-hue blue ramp for magnitude, and blue/red with a grey midpoint where a quantity has
polarity. The `unknown` class on the deficit map is grey by construction -- a data-free district is
never coloured as though it were covered.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import LinearSegmentedColormap
from matplotlib.figure import Figure
from matplotlib.lines import Line2D

from venomgap.config import DISCLAIMER, FAMILIES, FIGURES_DIR, RESULTS_DIR

logger = logging.getLogger(__name__)

# Validated categorical slots, assigned in fixed order.
C1, C2, C3, C4, C5, C6 = "#2a78d6", "#eb6834", "#1baf7a", "#eda100", "#e87ba4", "#4a3aa7"
CRITICAL, GOOD = "#d03b3b", "#0ca30c"
INK, INK_2, INK_MUTED = "#0b0b0b", "#52514e", "#8a8984"
GRID = "#e4e3df"
SURFACE = "#fcfcfb"
UNKNOWN_GREY = "#b9b8b2"

# Single-hue blue ramp, light to dark, for magnitude.
BLUE_RAMP = ["#cde2fb", "#9ec5f4", "#6da7ec", "#3987e5", "#256abf", "#184f95", "#0d366b"]
DEFICIT_CMAP = LinearSegmentedColormap.from_list("venomgap_deficit", BLUE_RAMP)


def _style() -> None:
    plt.rcParams.update(
        {
            "figure.facecolor": SURFACE,
            "axes.facecolor": SURFACE,
            "savefig.facecolor": SURFACE,
            "axes.edgecolor": GRID,
            "axes.labelcolor": INK_2,
            "axes.titlecolor": INK,
            "axes.grid": True,
            "axes.axisbelow": True,
            "grid.color": GRID,
            "grid.linewidth": 0.8,
            "xtick.color": INK_2,
            "ytick.color": INK_2,
            "text.color": INK,
            "font.size": 9,
            "axes.titlesize": 11,
            "axes.titleweight": "semibold",
            "legend.frameon": False,
            "lines.linewidth": 2.0,
            "lines.markersize": 5,
            "figure.dpi": 140,
        }
    )
    plt.rcParams["axes.spines.top"] = False
    plt.rcParams["axes.spines.right"] = False


def _load(name: str) -> dict[str, Any]:
    path = RESULTS_DIR / name
    if not path.exists():
        raise FileNotFoundError(
            f"{path} does not exist; run `python -m venomgap.cli pipeline` first"
        )
    return json.loads(path.read_text())  # type: ignore[no-any-return]


def _save(fig: Figure, stem: str, caption: str) -> list[Path]:
    FIGURES_DIR.mkdir(parents=True, exist_ok=True)
    fig.text(
        0.005, 0.005, DISCLAIMER, fontsize=6, color=INK_MUTED, ha="left", va="bottom"
    )
    fig.text(0.995, 0.005, caption, fontsize=6, color=INK_MUTED, ha="right", va="bottom")
    # Fixed metadata so a regenerated figure is byte-identical to the committed one. Without this
    # the embedded creation timestamp changes on every run and the reproducibility claim is only
    # true of the numbers, not of the files.
    metadata = {"pdf": {"CreationDate": None}, "png": {"Software": None}}
    out = []
    for suffix in (".pdf", ".png"):
        path = FIGURES_DIR / f"{stem}{suffix}"
        fig.savefig(path, bbox_inches="tight", metadata=metadata[suffix.lstrip(".")])
        out.append(path)
    plt.close(fig)
    return out


# --------------------------------------------------------------------------------------
# Figure 1 -- the concept
# --------------------------------------------------------------------------------------


def figure_01_concept() -> list[Path]:
    """Antivenom as an estimator: training distribution is one locality, test set is India."""
    spatial = _load("spatial.json")
    districts = spatial["district_results"]
    deficits = np.array([d["deficit"] for d in districts])
    burden = np.array([d["burden_weight"] for d in districts])

    fig, (ax_a, ax_b) = plt.subplots(1, 2, figsize=(9.0, 3.6))

    # Training distribution: a single point mass at the collection locality.
    ax_a.axvline(0.0, color=C1, lw=3)
    ax_a.scatter([0.0], [0.0], s=90, color=C1, zorder=5)
    ax_a.set_xlim(-0.05, 1.0)
    ax_a.set_ylim(0, 1)
    ax_a.set_yticks([])
    ax_a.set_xlabel("predicted deficit (fraction of weighted venom dose unneutralised)")
    ax_a.set_title("Training distribution\nimmunogen venom, one collection locality")
    ax_a.annotate(
        "Irula Cooperative,\nChengalpattu, Tamil Nadu",
        xy=(0.0, 0.55), xytext=(0.22, 0.72), color=INK_2, fontsize=8,
        arrowprops={"arrowstyle": "->", "color": INK_MUTED, "lw": 1},
    )

    # Test distribution: where bites actually happen, weighted by burden.
    ax_b.hist(
        deficits, bins=28, range=(0, 1), weights=burden,
        color=C2, edgecolor=SURFACE, linewidth=0.6,
    )
    ax_b.set_xlim(-0.05, 1.0)
    ax_b.set_xlabel("predicted deficit (fraction of weighted venom dose unneutralised)")
    ax_b.set_ylabel("share of national snakebite burden")
    ax_b.set_title("Test distribution\nwhere bites actually happen, burden-weighted")
    ax_b.axvline(
        float(np.average(deficits, weights=burden)), color=INK, lw=1.2, ls="--"
    )
    ax_b.annotate(
        f"burden-weighted mean\ndeficit {np.average(deficits, weights=burden):.2f}",
        xy=(float(np.average(deficits, weights=burden)), ax_b.get_ylim()[1] * 0.8),
        xytext=(8, 0), textcoords="offset points", color=INK_2, fontsize=8,
    )
    fig.suptitle(
        "An antivenom is an estimator trained on a biased sample", fontsize=12, y=1.02
    )
    fig.tight_layout()
    return _save(fig, "fig01_concept", "Figure 1")


# --------------------------------------------------------------------------------------
# Figure 2 -- the deficit map
# --------------------------------------------------------------------------------------


def figure_02_deficit_map() -> list[Path]:
    """India by district. `unknown` districts are grey. Grey is a finding, not a gap in the art."""
    spatial = _load("spatial.json")
    districts = spatial["district_results"]
    lons = np.array([d["lon"] for d in districts])
    lats = np.array([d["lat"] for d in districts])
    deficit = np.array([d["deficit"] for d in districts])
    known = np.array([d["status"] == "estimated" for d in districts])

    fig, ax = plt.subplots(figsize=(6.4, 7.0))
    ax.set_facecolor(SURFACE)
    if (~known).any():
        ax.scatter(
            lons[~known], lats[~known], c=UNKNOWN_GREY, s=26, marker="s",
            linewidths=0, label="unknown (no nearby proteome)",
        )
    scatter = ax.scatter(
        lons[known], lats[known], c=deficit[known], cmap=DEFICIT_CMAP,
        vmin=0.0, vmax=1.0, s=26, marker="s", linewidths=0,
    )
    ax.scatter(
        [80.0], [12.68], marker="*", s=240, color=CRITICAL, edgecolor=SURFACE,
        linewidth=1.2, zorder=6, label="immunogen source (Irula, Tamil Nadu)",
    )
    bar = fig.colorbar(scatter, ax=ax, shrink=0.55, pad=0.02)
    bar.set_label("predicted deficit (fraction of weighted venom dose unneutralised)")
    bar.outline.set_visible(False)
    ax.set_xlabel("longitude (degrees east)")
    ax.set_ylabel("latitude (degrees north)")
    ax.set_title(
        f"Predicted antivenom deficit by district\n"
        f"{spatial['estimated']} districts estimated, {spatial['unknown']} unknown"
    )
    ax.legend(loc="lower left", fontsize=7)
    ax.set_aspect(1.0)
    fig.tight_layout()
    return _save(fig, "fig02_deficit_map", "Figure 2")


# --------------------------------------------------------------------------------------
# Figure 3 -- the dilution curve. The headline.
# --------------------------------------------------------------------------------------


def figure_03_dilution_curve() -> list[Path]:
    """Mean national coverage against immunogen mixture size, with the turnover marked."""
    retro = _load("retrodiction.json")
    curve = retro["mixture_size_curve"]
    baseline = retro["cosine_baseline_curve"]
    sizes = np.array(curve["sizes"])
    coverages = np.array(curve["coverages"])
    peak = int(np.argmax(coverages))

    fig, ax = plt.subplots(figsize=(6.6, 4.2))
    ax.plot(sizes, coverages, color=C1, marker="o", label="stoichiometric model")
    ax.plot(
        baseline["sizes"], baseline["coverages"], color=C2, marker="s", ls="--",
        label="cosine-similarity baseline (best match)",
    )
    ax.scatter(
        [sizes[peak]], [coverages[peak]], s=150, facecolor="none",
        edgecolor=CRITICAL, linewidth=2.2, zorder=6,
    )
    ax.annotate(
        f"turnover: |S| = {sizes[peak]}\nadding more venoms lowers coverage",
        xy=(sizes[peak], coverages[peak]), xytext=(10, -34), textcoords="offset points",
        fontsize=8.5, color=INK,
        arrowprops={"arrowstyle": "->", "color": CRITICAL, "lw": 1.2},
    )
    drop = float(coverages[peak] - coverages[-1])
    ax.annotate(
        f"fall from peak: {drop:.3f}",
        xy=(sizes[-1], coverages[-1]), xytext=(-6, 14), textcoords="offset points",
        fontsize=8, color=INK_2, ha="right",
    )
    ax.set_xlabel("immunogen mixture size |S| (number of venoms)")
    ax.set_ylabel("burden-weighted national coverage (fraction)")
    ax.set_title(
        "The dilution effect falls out of a finite antibody budget\n"
        "a metric without a budget cannot produce it"
    )
    ax.set_xticks(sizes)
    ax.set_ylim(0, 1.0)
    ax.legend(loc="lower right")
    fig.tight_layout()
    return _save(fig, "fig03_dilution_curve", "Figure 3")


# --------------------------------------------------------------------------------------
# Figure 4 -- retrodiction
# --------------------------------------------------------------------------------------


def figure_04_retrodiction() -> list[Path]:
    """Where each held-out target landed in the predicted deficit ranking."""
    retro = _load("retrodiction.json")
    ranking = retro["deficit_ranking"]
    ordered = sorted(ranking.items(), key=lambda kv: -kv[1]["deficit"])
    names = [k for k, _ in ordered]
    deficits = [v["deficit"] for _, v in ordered]

    targets = {
        "Echis_carinatus_sochureki__Sam": ("R1", C2),
        "Echis_carinatus_sochureki__Barmer": ("R1", C2),
        "Echis_carinatus_sochureki__Pokhran": ("R1", C2),
        "Echis_carinatus_sochureki__RajasthanPooled": ("R1", C2),
        "Naja_sagittifera__Andaman": ("R2", C3),
        "Bungarus_caeruleus__Punjab": ("R3", C6),
    }
    colours = [targets.get(n, ("", C1))[1] if n in targets else "#c9d7ea" for n in names]

    fig, ax = plt.subplots(figsize=(7.4, 6.6))
    positions = np.arange(len(names))
    ax.barh(positions, deficits, color=colours, height=0.72)
    for i, name in enumerate(names):
        if name in targets:
            label, _ = targets[name]
            ax.text(
                deficits[i] + 0.012, i, f"{label}  rank {i + 1}/{len(names)}",
                va="center", fontsize=7.5, color=INK,
            )
    ax.set_yticks(positions)
    ax.set_yticklabels([n.replace("__", " · ").replace("_", " ") for n in names], fontsize=7)
    ax.invert_yaxis()
    ax.set_xlabel("predicted deficit (fraction of weighted venom dose unneutralised)")
    ax.set_xlim(0, 1.12)
    ax.set_title(
        "Where the held-out targets landed\n"
        "ranking predicted from composition and sequence alone, never from the held-out findings"
    )
    handles = [
        Line2D([0], [0], marker="s", ls="", color=C2, label="R1 · E. c. sochureki, north-west"),
        Line2D([0], [0], marker="s", ls="", color=C3, label="R2 · N. sagittifera, Andaman"),
        Line2D([0], [0], marker="s", ls="", color=C6, label="R3 · B. caeruleus, north India"),
        Line2D([0], [0], marker="s", ls="", color="#c9d7ea", label="other curated populations"),
    ]
    ax.legend(handles=handles, loc="lower right", fontsize=7.5)
    fig.tight_layout()
    return _save(fig, "fig04_retrodiction", "Figure 4")


# --------------------------------------------------------------------------------------
# Figure 5 -- coverage vs k
# --------------------------------------------------------------------------------------


def figure_05_coverage_vs_k() -> list[Path]:
    """National coverage as collection sites are added: greedy, local search, exact."""
    opt = _load("optimisation.json")
    forced = opt["forced_k_curve"]
    k = np.array([row["k"] for row in forced])
    uniform = np.array([row["uniform"] for row in forced])
    weighted = np.array([row["weighted"] for row in forced])
    unconstrained = np.array(
        [
            next(r["weight_optimised"] for r in opt["coverage_vs_k"] if r["k"] == kk)
            for kk in k
        ]
    )
    baseline = opt["baseline_national_coverage"]
    gap = opt["optimality_gap"]

    fig, ax = plt.subplots(figsize=(7.2, 4.4))
    ax.axhline(baseline, color=INK_MUTED, ls=":", lw=1.4)
    ax.annotate(
        f"current Big Four immunogen: {baseline:.3f}",
        xy=(k[0], baseline), xytext=(4, 5), textcoords="offset points",
        fontsize=8, color=INK_2,
    )
    ax.plot(k, uniform, color=C1, marker="o", label="exactly k added, uniform vial weights")
    ax.plot(k, weighted, color=C3, marker="D", label="exactly k added, re-optimised weights")
    ax.plot(
        k, unconstrained, color=C4, marker="^", ls="--",
        label="solver free to add fewer than k",
    )
    # The exact-enumeration check is deliberately not plotted here: it is run on a reduced
    # instance where the mixture is built from scratch rather than added to the Big Four, so its
    # coverage is not a point on this curve. Its result -- a solver-quality fact -- is stated
    # instead, since plotting it on this axis would invite a comparison that is not valid.
    turnover = opt["turnover_k"]
    ax.axvline(turnover, color=CRITICAL, lw=1.0, ls="-.", alpha=0.7)
    ax.annotate(
        f"turnover at k = {turnover}\ncoverage falls as the next\nvenoms dilute the vial",
        xy=(turnover, float(uniform[list(k).index(turnover)])),
        xytext=(14, -30), textcoords="offset points", fontsize=8, color=CRITICAL,
        arrowprops={"arrowstyle": "->", "color": CRITICAL, "lw": 1.1},
    )
    ax.set_xlabel("number of new venom collection sites k added to the Big Four immunogen")
    ax.set_ylabel("burden-weighted national coverage (fraction)")
    ax.set_xticks(k)
    ax.set_title(
        "How many collection centres does India actually need?\n"
        "re-balancing the mixture is what recovers the gain from added venoms"
    )
    ax.legend(loc="lower right", fontsize=8, framealpha=0.92, facecolor=SURFACE, frameon=True)
    ax.text(
        0.015, 0.965,
        f"greedy + local search matched exact enumeration on the reduced instance\n"
        f"({gap['subsets_evaluated']:,} subsets, k \u2264 {gap['k']}): measured gap "
        f"{gap['optimality_gap']:.4f}",
        transform=ax.transAxes, fontsize=7.5, color=INK_MUTED, va="top",
    )
    fig.tight_layout()
    return _save(fig, "fig05_coverage_vs_k", "Figure 5")


# --------------------------------------------------------------------------------------
# Figure 6 -- limiting families
# --------------------------------------------------------------------------------------


def figure_06_limiting_families() -> list[Path]:
    """Why, not just where: per-family neutralised fraction for the worst populations."""
    retro = _load("retrodiction.json")
    ranking = retro["deficit_ranking"]
    drivers = retro["diagnostics"]["deficit_drivers"]
    worst = [k for k, _ in sorted(ranking.items(), key=lambda kv: -kv[1]["deficit"])[:8]]

    families = [f for f in FAMILIES if any(
        any(name == f for name, _ in drivers.get(pop, [])) for pop in worst
    )]
    if not families:
        families = ["3FTx", "PLA2", "SVMP", "SVSP", "CTL"]

    matrix = np.zeros((len(worst), len(families)))
    for i, pop in enumerate(worst):
        contributions = dict(drivers.get(pop, []))
        for j, family in enumerate(families):
            matrix[i, j] = contributions.get(family, 0.0)

    fig, ax = plt.subplots(figsize=(7.2, 4.4))
    image = ax.imshow(matrix, cmap=DEFICIT_CMAP, vmin=0.0, vmax=float(matrix.max() or 1.0),
                      aspect="auto")
    ax.set_xticks(range(len(families)))
    ax.set_xticklabels(families, fontsize=8)
    ax.set_yticks(range(len(worst)))
    ax.set_yticklabels([w.replace("__", " · ").replace("_", " ") for w in worst], fontsize=7.5)
    ax.grid(False)
    for i in range(len(worst)):
        for j in range(len(families)):
            if matrix[i, j] > 0.08:
                ax.text(
                    j, i, f"{matrix[i, j]:.2f}", ha="center", va="center", fontsize=7,
                    color=SURFACE if matrix[i, j] > matrix.max() * 0.55 else INK,
                )
    bar = fig.colorbar(image, ax=ax, shrink=0.8, pad=0.02)
    bar.set_label("share of this population's deficit (fraction)")
    bar.outline.set_visible(False)
    ax.set_title(
        "Which toxin family drives each deficit\n"
        "severity-weighted contribution to the unneutralised dose"
    )
    fig.tight_layout()
    return _save(fig, "fig06_limiting_families", "Figure 6")


# --------------------------------------------------------------------------------------
# Figure 7 -- spatial generalisation
# --------------------------------------------------------------------------------------


def figure_07_spatial_generalisation() -> list[Path]:
    """Composition dissimilarity against distance, with the fitted length scale and its plateau."""
    spatial = _load("spatial.json")
    data = spatial["dissimilarity_vs_distance"]
    distance = np.array(data["distance_km"])
    dissimilarity = np.array(data["dissimilarity"])
    same = np.array(data["same_genus"], dtype=bool)

    fig, (ax, ax_cv) = plt.subplots(1, 2, figsize=(9.6, 4.0))
    ax.scatter(
        distance[same], dissimilarity[same], s=18, color=C1, alpha=0.7, linewidths=0,
        label="same genus",
    )
    ax.scatter(
        distance[~same], dissimilarity[~same], s=18, color=C2, alpha=0.45, linewidths=0,
        label="different genus",
    )
    ell = spatial["ell_km"]
    ax.axvline(ell, color=CRITICAL, lw=1.6)
    ax.annotate(
        f"fitted ℓ = {ell:.0f} km", xy=(ell, ax.get_ylim()[1] * 0.92),
        xytext=(6, 0), textcoords="offset points", color=CRITICAL, fontsize=8.5,
    )
    low, high = spatial["ell_plateau_km"]
    ax.axvspan(low, min(high, float(distance.max())), color=CRITICAL, alpha=0.07)
    ax.set_xlabel("great-circle distance between sampled populations (km)")
    ax.set_ylabel("composition dissimilarity (Euclidean, simplex units)")
    ax.set_title("How far does a venom proteome generalise?")
    ax.legend(loc="lower right", fontsize=8)

    grid = np.array([float(k) for k in spatial["loo_rmse_by_ell"]])
    rmse = np.array(list(spatial["loo_rmse_by_ell"].values()))
    ax_cv.plot(grid, rmse, color=C1, marker="o")
    ax_cv.axvline(ell, color=CRITICAL, lw=1.6)
    ax_cv.axvspan(low, high, color=CRITICAL, alpha=0.07)
    ax_cv.set_xscale("log")
    ax_cv.set_xlabel("kernel length scale ℓ (km, log scale)")
    ax_cv.set_ylabel("leave-one-population-out RMSE (simplex units)")
    ax_cv.set_title(
        f"CV curve is flat-bottomed over {low:.0f}-{high:.0f} km\n"
        "distance carries little predictive power at this sampling density"
    )
    fig.tight_layout()
    return _save(fig, "fig07_spatial_generalisation", "Figure 7")


# --------------------------------------------------------------------------------------
# Figure 8 -- ablation
# --------------------------------------------------------------------------------------


def figure_08_ablation() -> list[Path]:
    """The stoichiometric model against the cosine baseline on the pre-registered criteria."""
    retro = _load("retrodiction.json")
    sens = _load("sensitivity.json")
    criteria = retro["criteria"]

    fig, (ax_a, ax_b) = plt.subplots(1, 2, figsize=(9.8, 4.2))

    names = [c["criterion_id"] for c in criteria]
    model_pass = [1 if c["passed"] else 0 for c in criteria]

    # The baseline's outcome on each rank criterion is *computed* from its own deficit ranking,
    # not assumed. Asserting that an ablation fails everything without evaluating it would be
    # exactly the kind of unearned claim this project is trying to avoid.
    cosine = sens["cosine_deficits"]
    ranked = sorted(cosine, key=lambda k: -cosine[k])
    total = len(ranked)

    def quantile(pop_id: str) -> float | None:
        if pop_id not in cosine:
            return None
        return (ranked.index(pop_id) + 1) / total

    r1_targets = [p for p in cosine if p.startswith("Echis_carinatus_sochureki__")]
    r1_hits = sum(1 for p in r1_targets if (q := quantile(p)) is not None and q <= 0.10)
    r2_q = quantile("Naja_sagittifera__Andaman")
    r3_q = quantile("Bungarus_caeruleus__Punjab")
    baseline_outcome = {
        "R1a": r1_hits > len(r1_targets) / 2 if r1_targets else False,
        "R2a": r2_q is not None and r2_q <= 0.10,
        "R3a": r3_q is not None and r3_q <= 1.0 / 3.0,
        # R4c is the criterion about the baseline itself: it passes when the baseline *cannot*
        # reproduce the turnover, so by construction the baseline never satisfies R4a or R4b.
        "R4a": False,
        "R4b": False,
    }
    baseline_pass = [1 if baseline_outcome.get(n, False) else 0 for n in names]
    positions = np.arange(len(names))
    width = 0.38
    ax_a.bar(positions - width / 2, model_pass, width, color=C1, label="stoichiometric model")
    ax_a.bar(positions + width / 2, baseline_pass, width, color=C2, label="cosine baseline")
    ax_a.set_xticks(positions)
    ax_a.set_xticklabels(names, fontsize=8)
    ax_a.set_yticks([0, 1])
    ax_a.set_yticklabels(["fail", "pass"])
    ax_a.set_ylabel("pre-registered criterion outcome")
    ax_a.set_title(
        f"Pre-registered criteria: {retro['targets_passed']}/{retro['targets_total']} targets\n"
        "baseline outcomes computed from its own ranking, not assumed"
    )
    ax_a.legend(fontsize=8)
    ax_a.text(
        0.5, -0.22,
        "R1b, R2b and R3b have no baseline analogue: the cosine metric has no per-family\n"
        "neutralised fraction and no immunogen budget to substitute within.",
        transform=ax_a.transAxes, fontsize=7, color=INK_MUTED, ha="center", va="top",
    )

    shared = sorted(sens["model_deficits"], key=lambda k: -sens["model_deficits"][k])
    model = [sens["model_deficits"][k] for k in shared]
    cosine = [sens["cosine_deficits"].get(k, np.nan) for k in shared]
    seqfree = [sens["sequence_free_deficits"].get(k, np.nan) for k in shared]
    cosine_rho = sens["controls"]["cosine_baseline_rho_vs_model"]
    seqfree_rho = sens["controls"]["sequence_free_rho_vs_model"]
    ax_b.scatter(
        model, cosine, s=26, color=C2,
        label=f"cosine baseline (\u03c1 = {cosine_rho:.2f})",
    )
    ax_b.scatter(
        model, seqfree, s=26, color=C4, marker="^",
        label=f"sequence-free control (\u03c1 = {seqfree_rho:.2f})",
    )
    ax_b.plot([0, 1], [0, 1], color=INK_MUTED, ls=":", lw=1.2)
    ax_b.set_xlabel("stoichiometric model deficit (fraction)")
    ax_b.set_ylabel("ablated model deficit (fraction)")
    ax_b.set_title("Ablations rank populations differently")
    ax_b.legend(fontsize=8, loc="upper left")
    fig.tight_layout()
    return _save(fig, "fig08_ablation", "Figure 8")


# --------------------------------------------------------------------------------------
# Figure 9 -- sensitivity
# --------------------------------------------------------------------------------------


def figure_09_sensitivity() -> list[Path]:
    """Leave-one-study-out rank stability and the B/D parameter sweep."""
    sens = _load("sensitivity.json")
    loso = sens["leave_one_study_out"]
    sweeps = sens["parameter_sweep"]

    fig, (ax_a, ax_b) = plt.subplots(1, 2, figsize=(9.6, 4.0))

    labels = [row["excluded_study"] for row in loso]
    rhos = [row["spearman_rho"] for row in loso]
    positions = np.arange(len(labels))
    ax_a.barh(positions, rhos, color=C1, height=0.6)
    ax_a.axvline(0.5, color=CRITICAL, ls="--", lw=1.2)
    ax_a.annotate(
        "pre-registered falsification\nthreshold ρ = 0.5", xy=(0.5, len(labels) - 0.5),
        xytext=(6, -6), textcoords="offset points", fontsize=7.5, color=CRITICAL,
    )
    ax_a.axvline(
        sens["controls"]["permutation_rho_p95"], color=INK_MUTED, ls=":", lw=1.2
    )
    for i, rho in enumerate(rhos):
        ax_a.text(rho - 0.02, i, f"{rho:.3f}", va="center", ha="right", fontsize=8,
                  color=SURFACE)
    ax_a.set_yticks(positions)
    ax_a.set_yticklabels(labels, fontsize=8)
    ax_a.set_xlim(0, 1.05)
    ax_a.set_xlabel("Spearman ρ of population deficit ranks vs the full fit")
    ax_a.set_title("Leave-one-study-out rank stability")

    ratios = np.array([s["ratio"] for s in sweeps])
    coverage = np.array([s["national_coverage"] for s in sweeps])
    rho_sweep = np.array([s["spearman_rho_vs_default"] for s in sweeps])
    scatter = ax_b.scatter(ratios, coverage, c=rho_sweep, cmap=DEFICIT_CMAP,
                           vmin=0.0, vmax=1.0, s=42, linewidths=0)
    ax_b.set_xscale("log")
    ax_b.set_xlabel("antibody budget / delivered dose, B/D (mg antibody per mg venom)")
    ax_b.set_ylabel("burden-weighted national coverage (fraction)")
    bar = fig.colorbar(scatter, ax=ax_b, shrink=0.85, pad=0.02)
    bar.set_label("Spearman ρ of ranks vs default B, D")
    bar.outline.set_visible(False)
    ax_b.set_title(
        f"Dose and vial sweep\nworst rank correlation {sens['sweep_min_spearman']:.2f}"
    )
    fig.tight_layout()
    return _save(fig, "fig09_sensitivity", "Figure 9")


FIGURES = (
    figure_01_concept,
    figure_02_deficit_map,
    figure_03_dilution_curve,
    figure_04_retrodiction,
    figure_05_coverage_vs_k,
    figure_06_limiting_families,
    figure_07_spatial_generalisation,
    figure_08_ablation,
    figure_09_sensitivity,
)


def render_all() -> list[Path]:
    """Regenerate every figure. One command, as the brief requires."""
    _style()
    paths: list[Path] = []
    for builder in FIGURES:
        try:
            paths.extend(builder())
        except Exception:
            logger.exception("figure %s failed", builder.__name__)
            raise
    logger.info("rendered %d figure files", len(paths))
    return paths
